version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.remix
    environment:
      - SERVER_PORT=server:8080
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - MYSQL_HOST=db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8.2
#    restart: always
    environment:
      MYSQL_DATABASE: 'db'
#      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - "./data:/docker-entrypoint-initdb.d"