FROM openjdk:17-jdk-slim-buster

RUN apt update && apt upgrade -y
#RUN apt install -y gradle

WORKDIR /build

COPY ./ .

RUN ./gradlew tasks
RUN mkdir /app
RUN ./gradlew assembleDist && cp server/build/libs/server-*-SNAPSHOT.jar /app

WORKDIR /app

ENTRYPOINT java -jar server-*-SNAPSHOT.jar